# Generated by Django 6.0.4 on 2026-06-18 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, help_text="Safaricom's CheckoutRequestId for matching callback responses", max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-pesa'), ('cash_on_delivery', 'Cash on Delivery')], default='cash_on_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: 2547XXXXXXXX (used for Mpesa STK Push)', max_length=15),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['mpesa_checkout_request_id'], name='checkout_or_mpesa_c_7adf79_idx'),
        ),
    ]
