# Generated by Django 6.0.4 on 2026-05-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number_required',
            new_name='phone_number_provided',
        ),
    ]
